package entidades;
// Generated 10-abr-2023 18:23:04 by Hibernate Tools 4.3.1



/**
 * PedidoProducto generated by hbm2java
 */
public class PedidoProducto  implements java.io.Serializable {


     private PedidoProductoId id;
     private Pedido pedido;
     private Producto producto;
     private double cantidad;
     private String estado;

    public PedidoProducto() {
    }

    public PedidoProducto(PedidoProductoId id, Pedido pedido, Producto producto, double cantidad, String estado) {
       this.id = id;
       this.pedido = pedido;
       this.producto = producto;
       this.cantidad = cantidad;
       this.estado = estado;
    }
   
    public PedidoProductoId getId() {
        return this.id;
    }
    
    public void setId(PedidoProductoId id) {
        this.id = id;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


