package entidades;
// Generated 10-abr-2023 18:23:04 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private int id;
     private Usuario usuarioByIdCliente;
     private Usuario usuarioByIdTrabajador;
     private Date fecha;
     private Set usuarios = new HashSet(0);
     private Set pedidoProductos = new HashSet(0);
     private Set establecimientos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(int id, Usuario usuarioByIdCliente, Usuario usuarioByIdTrabajador, Date fecha) {
        this.id = id;
        this.usuarioByIdCliente = usuarioByIdCliente;
        this.usuarioByIdTrabajador = usuarioByIdTrabajador;
        this.fecha = fecha;
    }
    public Pedido(int id, Usuario usuarioByIdCliente, Usuario usuarioByIdTrabajador, Date fecha, Set usuarios, Set pedidoProductos, Set establecimientos) {
       this.id = id;
       this.usuarioByIdCliente = usuarioByIdCliente;
       this.usuarioByIdTrabajador = usuarioByIdTrabajador;
       this.fecha = fecha;
       this.usuarios = usuarios;
       this.pedidoProductos = pedidoProductos;
       this.establecimientos = establecimientos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuario getUsuarioByIdCliente() {
        return this.usuarioByIdCliente;
    }
    
    public void setUsuarioByIdCliente(Usuario usuarioByIdCliente) {
        this.usuarioByIdCliente = usuarioByIdCliente;
    }
    public Usuario getUsuarioByIdTrabajador() {
        return this.usuarioByIdTrabajador;
    }
    
    public void setUsuarioByIdTrabajador(Usuario usuarioByIdTrabajador) {
        this.usuarioByIdTrabajador = usuarioByIdTrabajador;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getPedidoProductos() {
        return this.pedidoProductos;
    }
    
    public void setPedidoProductos(Set pedidoProductos) {
        this.pedidoProductos = pedidoProductos;
    }
    public Set getEstablecimientos() {
        return this.establecimientos;
    }
    
    public void setEstablecimientos(Set establecimientos) {
        this.establecimientos = establecimientos;
    }




}


