package entidades;
// Generated 10-abr-2023 18:23:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int id;
     private Establecimiento establecimiento;
     private String nombre;
     private String descripcion;
     private double precio;
     private byte[] imagen;
     private int stock;
     private Set pedidoProductos = new HashSet(0);
     private Set categorias = new HashSet(0);

    public Producto() {
    }

	
    public Producto(int id, Establecimiento establecimiento, String nombre, String descripcion, double precio, byte[] imagen, int stock) {
        this.id = id;
        this.establecimiento = establecimiento;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.precio = precio;
        this.imagen = imagen;
        this.stock = stock;
    }
    public Producto(int id, Establecimiento establecimiento, String nombre, String descripcion, double precio, byte[] imagen, int stock, Set pedidoProductos, Set categorias) {
       this.id = id;
       this.establecimiento = establecimiento;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.imagen = imagen;
       this.stock = stock;
       this.pedidoProductos = pedidoProductos;
       this.categorias = categorias;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Establecimiento getEstablecimiento() {
        return this.establecimiento;
    }
    
    public void setEstablecimiento(Establecimiento establecimiento) {
        this.establecimiento = establecimiento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public Set getPedidoProductos() {
        return this.pedidoProductos;
    }
    
    public void setPedidoProductos(Set pedidoProductos) {
        this.pedidoProductos = pedidoProductos;
    }
    public Set getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Set categorias) {
        this.categorias = categorias;
    }




}


